spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./db/katasimple
    username: katasimple
    password: katasimple
  flyway:
    schemas: PUBLIC

  jooq:
    sql-dialect: h2
  h2:
    console:
      enabled: true
